In [15]:
import random
from importlib import reload
import numpython.base as base

import numpy as np

In [45]:
np.random.random((4,4))

array([[0.41644363, 0.34246703, 0.60761662, 0.69950342],
       [0.0097792 , 0.88251805, 0.25575945, 0.63002603],
       [0.11853626, 0.02555939, 0.77059959, 0.49321939],
       [0.26106576, 0.45340015, 0.77882249, 0.48211265]])

In [21]:
ar = np.array(range(16)).reshape((4,4))

In [125]:
print(ar)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [163]:
reload(base)

<module 'numpython.base' from 'd:\\numpython\\numpython\\numpython\\base.py'>

In [149]:
mat = base.Pymatrix.from_numpy(ar)

In [123]:
mat

Pymatrix(4, 4)

In [119]:
print(mat)

Pymatrix([[  0,   1,   2,   3],
          [  4,   5,   6,   7],
          [  8,   9,  10,  11],
          [ 12,  13,  14,  15]])


In [164]:
lst = list(range(25))
chunks = [lst[i:i + 5] for i in range(0, len(lst), 5)]

In [165]:
matrix = base.Pymatrix(chunks)

In [166]:
matrix

Pymatrix([[  0,   1,   2,   3,   4],
          [  5,   6,   7,   8,   9],
          [ 10,  11,  12,  13,  14],
          [ 15,  16,  17,  18,  19],
          [ 20,  21,  22,  23,  24]])

In [183]:
type(matrix[2])

list

In [175]:
s =slice(1, 3)

In [181]:
type(slice(1, 3))

slice

In [179]:
s.start

1

In [160]:
matrix[2, 0]

101

In [137]:
print(matrix)

[[  0,   1,   2,   3,   4]
 [  5,   6,   7,   8,   9]
 [ 10,  11,  12,  13,  14]
 [ 15,  16,  17,  18,  19]
 [ 20,  21,  22,  23,  24]]


In [5]:
zero_matrix = base.Pymatrix.random(5, 5)

In [6]:
zero_matrix.cols

5